create or replace PROCEDURE NEW_CERTIFICATION
  (
    C_NOMBRE IN CERTIFICATION.CERTIFICATION_TITLE%TYPE,
    I_ID IN INSTITUTION.ID%TYPE,
    I_NOMBRE IN INSTITUTION.INSTITUTION_NAME%TYPE,
    I_TIPO IN INSTITUTION.INSTITUTION_TYPE%TYPE
  )
IS
  --CERTIFICACION NUEVA DESDE LA PETICION - CN
  V_CN_ID      CERTIFICATION.CERTIFICATION_ID%TYPE; --N/A
  V_CN_NOMBRE  CERTIFICATION.CERTIFICATION_TITLE%TYPE := LOWER(C_NOMBRE);
  V_CN_CODIGO  CERTIFICATION.CERTIFICATION_CODE%TYPE  := CREATE_SLUG(V_CN_NOMBRE);


  --INSTITUCION VIEJA DESDE LA PETICION - I
  V_I_ID      INSTITUTION.ID%TYPE := I_ID;

  --INSTITUCION NUEVA - IN
  V_IN_ID     INSTITUTION.ID%TYPE;
  V_IN_CODIGO INSTITUTION.INSTITUTION_CODE%TYPE;
  V_IN_NOMBRE INSTITUTION.INSTITUTION_NAME%TYPE := LOWER(I_NOMBRE);
  V_IN_TIPO   INSTITUTION.INSTITUTION_TYPE%TYPE := I_TIPO;

  --VARIABLES VERIFICACION DE GUARDADO. -G
  V_G_I NUMBER;
  V_G_C NUMBER;

  BEGIN

    --SI SE SELECCIONA DESDE EL SELECT
    IF V_I_ID != 0 THEN

      -- seguarda el valor de la secuencna en el nuevo valor de la
      -- certificacion
      SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_CN_ID FROM DUAL;


      -------INSERCION LA CERTIFICACION---------
      V_G_C := CREAR_CERTIFICACION(V_CN_ID,V_CN_NOMBRE,V_CN_CODIGO,V_I_ID);

      -- 1 significa error desde la funcion
      IF V_G_C = 1 THEN

        RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAD, PORQ YA EXISTE LA CERTIFICACION');

      END IF;

    ELSE --SI SE DIJITA POR EL USUARIO

      --RETORNA 0 EN CASO DE NO ENCONTRARLA.
      V_IN_ID := FIND_INSTITUTION(V_IN_NOMBRE);

      --NO ENCONTRO LA INSTITUCION.
      IF V_IN_ID = 0 THEN

        SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_IN_ID FROM DUAL;

        V_IN_CODIGO := CREATE_SLUG(V_IN_NOMBRE);

        -------INSERCION LA INSTITUCION---------
        V_G_I := CREAR_INSTITUCION(V_IN_ID,V_IN_NOMBRE,V_IN_CODIGO,V_IN_TIPO);

        SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_CN_ID FROM DUAL;

        -------INSERCION LA CERTIFICACION---------
        V_G_C := CREAR_CERTIFICACION(V_CN_ID,V_CN_NOMBRE,V_CN_CODIGO,V_IN_ID);

        IF V_G_C = 1 THEN

          RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAD, PORQ YA EXISTE LA CERTIFICACION');

        END IF;

      ELSE --YA EXISTE INSTITUCION

        SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_CN_ID FROM DUAL;

        -------INSERCION LA CERTIFICACION---------
        V_G_C := CREAR_CERTIFICACION(V_CN_ID,V_CN_NOMBRE,V_CN_CODIGO,V_IN_ID);

        -- 1 significa error desde la funcion
        IF V_G_C = 1 THEN

          RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAR, PORQ YA EXISTE LA CERTIFICACION');

        END IF;

      END IF;

    END IF;


  END NEW_CERTIFICATION;