CREATE OR REPLACE PROCEDURE CA_AREA --CA = CREAR / ACTUALIZAR
  (
    A_NOMBRE IN AREA.NOMBRE%TYPE, --DEFINIENDO VARIABLE DEL PROC
    A_ID IN AREA.ID%TYPE            --DEFINIENDO VARIABLE DEL PROC
  )
IS
  --CERTIFICACION NUEVA DESDE LA PETICION - CN
  V_AN_ID      AREA.ID%TYPE := A_ID; --N/A
  V_AN_NOMBRE  AREA.NOMBRE%TYPE := A_NOMBRE;

  --VARIABLES VERIFICACION DE GUARDADO. -G
  V_G_A NUMBER; --GUARDARA EL RESULTADO DE LA FUNCION CREAR_AREA
  TOTAL NUMBER; --GUARDARA EL RESULTADO DEL CONTEO DE VERIFICACION DE UN REGISTRO

  BEGIN

    --SI El ID ES 0 SE TRATA DE UN NUEVO REGISTRO
    IF V_AN_ID = 0 THEN

      -- seguarda el valor de la secuencna en el nuevo valor del
      -- area
      SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_AN_ID FROM DUAL;

      -------INSERCION DEL AREA USANDO LA FUNCION CREAR_AREA---------
      V_G_A := CREAR_AREA(V_AN_ID,V_AN_NOMBRE);

      -- 1 SIGNIFICA QUE NO SE PUDO CREAR EL AREA, VIENE DESDE LA FUNCION
      IF V_G_A = 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAR, PORQUE YA EXISTE EL AREA');
      END IF;

    ELSE --SI NO ES 0 SE DEBE VERIFICAR SI EXISTE EL REGISTRO, SI EXISTE SE ACTUALIZA, SINO SE CREA
        -----VERIFICANDO SI EXISTE EL REGISTRO
        TOTAL := 0;
        SELECT COUNT(*) INTO TOTAL FROM AREA WHERE ID = V_AN_ID;

        IF TOTAL = 0 THEN -- SI EL TOTAL ES 0 NO SE ENCONTRO REGISTRO ALGUNO CON EL ID
                            --QUE VIENE DESDE LA APLICACION ENTONCES CREA EL REGISTRO
            -------INSERCION DEL AREA---------
            V_G_A := CREAR_AREA(V_AN_ID,V_AN_NOMBRE);

            -- 1 SIGNIFICA QUE NO SE PUDO CREAR
            IF V_G_A = 1 THEN
              RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAR, PORQUE YA EXISTE EL AREA');
            END IF;

        ELSE --SI EL TOTAL ES DIFERENTE DE 0 ENTONCES ENCONTRO REGISTRO Y LO ACTUALIZA
            -------ACTUALIZACION DEL AREA----------------
            V_G_A :=ACTUALIZAR_AREA(V_AN_ID,V_AN_NOMBRE);

            -- 1 SIGNIFICA QUE NO SE PUDO ACTUALIZAR
            IF V_G_A = 1 THEN
                Raise_Application_Error(-20001, 'La certificacion no se pudo actualizar');
            END IF;

        END IF;
    END IF;
  END CA_AREA;