create or replace PROCEDURE SP_CREAR_JOB_PRO_LANG
  (
      ID_PERFIL      IN JOB_PROFILES.ID%TYPE
    , ID_NIVEL       IN LANGUAGE_LEVEL.LANGUAGE_LEVEL_ID%TYPE
    , ID_LENGUAJE    IN LANGUAGES.LANGUAGE_ID%TYPE
  ) IS
  V_RESULTADO NUMBER;
  BEGIN

    V_RESULTADO := CREAR_JOB_PRO_LANG(ID_LENGUAJE,ID_NIVEL,ID_PERFIL);

    IF V_RESULTADO = -3 THEN
      RAISE_APPLICATION_ERROR(-20003, 'Ya existe el registro de este lenguaje para este perfil');
    END IF;


  END SP_CREAR_JOB_PRO_LANG;