create or replace PROCEDURE SP_CREAR_EXP_ACADEMICA_PERFIL
  (
      ID_PERFIL IN NUMBER
    , ID_TITULO IN NUMBER
    , NOMBRE_TITULO IN VARCHAR2
  ) IS
  V_TITLE_NAME ACADEMIC_TITLES.TITLE%TYPE := LOWER(NOMBRE_TITULO);
  V_RESULTADO NUMBER;
  V_RESULT_TITLE NUMBER;
  BEGIN

    V_RESULTADO := CREAR_EXP_ACADEMICA_PERFIL(ID_PERFIL,ID_TITULO);

    IF V_RESULTADO = -1 THEN

      V_RESULT_TITLE := CREAR_TITULO(NOMBRE_TITULO);

      IF V_RESULT_TITLE > 0 THEN
        V_RESULTADO := CREAR_EXP_ACADEMICA_PERFIL(ID_PERFIL,V_RESULT_TITLE);
      END IF;

    ELSIF V_RESULTADO = -2 THEN
      RAISE_APPLICATION_ERROR(-20002, 'El perfil no existe');
    elsif v_resultado = -3 THEN
      RAISE_APPLICATION_ERROR(-20003, 'Ya existe el registro de este cargo para este perfil');
    elsif v_resultado = -4 THEN
      RAISE_APPLICATION_ERROR(-20004, 'La experiencia no puede ser negativa o igual a cero');
    END IF;


  END SP_CREAR_EXP_ACADEMICA_PERFIL;