create or replace PROCEDURE SP_CREAR_JOB_PRO_SKILL
  (
      ID_HABILIDAD      IN SKILL.SKILL_ID%TYPE
    , NOMBRE_HABILIDAD  IN SKILL.TITULO%TYPE
    , ID_PERFIL         IN JOB_PROFILES.ID%TYPE
    , ID_CATEGORIA      IN SKILL_CATEGORY.SKILL_CATEGORY_ID%TYPE
  ) IS
  V_SKILL_NAME SKILL.TITULO%TYPE := LOWER(NOMBRE_HABILIDAD);
  V_RESULTADO NUMBER;
  V_RESUL_SKILL NUMBER;
  BEGIN

    V_RESULTADO := CREAR_JOB_PRO_SKILL(ID_HABILIDAD,V_SKILL_NAME,ID_PERFIL,ID_CATEGORIA);

    IF V_RESULTADO = -1 THEN

      V_RESUL_SKILL := CREAR_HABILIDAD(V_SKILL_NAME,ID_CATEGORIA);

      IF V_RESUL_SKILL > 0 THEN
        V_RESULTADO := CREAR_JOB_PRO_SKILL(V_RESUL_SKILL,V_SKILL_NAME,ID_PERFIL,ID_CATEGORIA);
      END IF;

    ELSIF V_RESULTADO = -2 THEN
      RAISE_APPLICATION_ERROR(-20002, 'El perfil no existe');
    ELSIF v_resultado = -3 THEN
      RAISE_APPLICATION_ERROR(-20003, 'Ya existe el registro de esta habilidad para este perfil');
    END IF;


  END SP_CREAR_JOB_PRO_SKILL;