CREATE OR REPLACE PROCEDURE CA_EXAM --CA = CREAR / ACTUALIZAR
  (
    E_ID            IN EXAM.ID%TYPE,
    E_FECHA         IN EXAM.FECHA%TYPE,
    E_INSTRUCCIONES IN EXAM.INSTRUCCIONES%TYPE,
    E_PUBLICADO     IN EXAM.PUBLICADO%TYPE,
    E_SUBAREA_ID    IN EXAM.SUB_AREA_ID%TYPE,
    E_TITULO        IN EXAM.TITULO%TYPE
  )
IS
  --REGISTRO NUEVO DESDE LA PETICION - EN
  V_EN_ID           EXAM.ID%TYPE := E_ID; --N/A
  V_EN_FECHA        EXAM.FECHA%TYPE := E_FECHA;
  V_EN_INSTRUCCIONES EXAM.INSTRUCCIONES%TYPE := E_INSTRUCCIONES;
  V_EN_PUBLICADO    EXAM.PUBLICADO%TYPE := E_PUBLICADO;
  V_EN_SUBAREA_ID   EXAM.SUB_AREA_ID%TYPE := E_SUBAREA_ID;
  V_EN_TITULO       EXAM.TITULO%TYPE := E_TITULO;

  --VARIABLES VERIFICACION DE GUARDADO. -G
  V_G NUMBER;
  TOTAL NUMBER;

  BEGIN

    --SI El ID ES 0 SE TRATA DE UN NUEVO REGISTRO
    IF V_EN_ID = 0 THEN

      -- seguarda el valor de la secuencia en el nuevo valor de la
      -- subarea
      SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_EN_ID FROM DUAL;

      -------INSERCION DE LA SUBAREA USANDO LA FUNCION CREAR_SUBAREA---------
      V_G := CREAR_EXAM(V_EN_ID,V_EN_FECHA,V_EN_INSTRUCCIONES,V_EN_PUBLICADO,V_EN_SUBAREA_ID,V_EN_TITULO);

      -- 1 significa error desde la funcion
      IF V_G = 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAR, PORQUE YA EXISTE EL EXAMEN');
      END IF;

    ELSE --SI SE DIJITA POR EL USUARIO
        TOTAL := 0;
        SELECT COUNT(*) INTO TOTAL FROM EXAM WHERE ID = V_EN_ID;

        IF TOTAL = 0 THEN -- SI EL TOTAL ES 0 NO SE ENCONTRO
                            --REGISTRO CON ESE ID ENTONCES LO CREA
            -------INSERCION DEL SUBAREA---------
            V_G := CREAR_EXAM(V_EN_ID,V_EN_FECHA,V_EN_INSTRUCCIONES,V_EN_PUBLICADO,V_EN_SUBAREA_ID,V_EN_TITULO);

            -- 1 significa error desde la funcion
            IF V_G = 1 THEN
              RAISE_APPLICATION_ERROR(-20001, 'NO SE PUDO GUARDAR, PORQUE YA EXISTE EL SUBAREA');
            END IF;

        ELSE --SI ENCONTRO REGISTRO ENTONCES LA ACTUALIZA

            V_G := ACTUALIZAR_EXAM(V_EN_ID,V_EN_FECHA,V_EN_INSTRUCCIONES,V_EN_PUBLICADO,V_EN_SUBAREA_ID,V_EN_TITULO);

            IF V_G = 1 THEN
                Raise_Application_Error(-20001, 'El examen no se pudo actualizar');
            END IF;

        END IF;
    END IF;
  END CA_EXAM;