CREATE OR REPLACE FUNCTION ACTUALIZAR_PREGUNTA
  (
      ID_Q IN NUMBER
    , D1_Q IN VARCHAR2
    , D2_Q IN VARCHAR2
    , D3_Q IN VARCHAR2
    , D4_Q IN VARCHAR2
    , ENUNCIADO_Q IN VARCHAR2
    , PESO_Q IN NUMBER
    , RESPUESTA_Q IN VARCHAR2
    , SUBAREA_ID_Q IN NUMBER
  ) RETURN NUMBER
IS
  ---DECLARACION DE VARIABLES--
  BEGIN

    UPDATE QUESTION SET
                D1 = D1_Q,
                D2 = D2_Q,
                D3 = D3_Q,
                D4 = D4_Q,
                ENUNCIADO = ENUNCIADO_Q,
                PESO = PESO_Q,
                RESPUESTA = RESPUESTA_Q,
                SUB_AREA_ID = SUBAREA_ID_Q
                WHERE ID = ID_Q;
    RETURN 0; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1;  --SIGNIFICA ERROR

  END ACTUALIZAR_PREGUNTA;