CREATE OR REPLACE FUNCTION ACTUALIZAR_CUESTIONARIO
  (
      ID_C    IN NUMBER
    , EXAM_ID_C IN NUMBER
    , QUESTION_ID_C  IN NUMBER
  ) RETURN NUMBER --RETORNARA UN NUMERO
IS
  -- AQUI SE DECLARAN VARIABLES
   --
  BEGIN
    --ACTUALIZA EL REGISTRO
    UPDATE QUESTIONARY SET
                EXAM_ID = EXAM_ID_C,
                QUESTION_ID = QUESTION_ID_C
                WHERE ID = ID_C;

    RETURN 0; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1;  --SIGNIFICA ERROR

  END ACTUALIZAR_CUESTIONARIO;