CREATE OR REPLACE FUNCTION ACTUALIZAR_AREA
  (
      A_ID IN NUMBER --PARAMETRO DE LA FUNCION
    , A_NOMBRE IN VARCHAR2 --PARAMETRO DE LA FUNCION
  ) RETURN NUMBER --TIPO DE RETORNO
IS
  -- AQUI SE DECLARAN VARIABLES
   --
  BEGIN
    --ACTUALIZA EL REGISTRO
    UPDATE AREA SET
                NOMBRE = A_NOMBRE
                WHERE ID = A_ID;

    RETURN 0; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1;  --SIGNIFICA ERROR

  END ACTUALIZAR_AREA;