create or replace FUNCTION FIND_INSTITUTION
  (
    NOMBRE IN VARCHAR2
  ) RETURN INSTITUTION.ID%TYPE
IS
  --INSTITUCION - I
  V_I_CODE INSTITUTION.INSTITUTION_CODE%TYPE;
  V_I_ID INSTITUTION.ID%TYPE;
  BEGIN

    V_I_CODE := CREATE_SLUG(NOMBRE);

    SELECT ID INTO V_I_ID FROM INSTITUTION WHERE INSTITUTION_CODE = V_I_CODE;

    RETURN V_I_ID;

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    RETURN 0;

  END FIND_INSTITUTION;