CREATE OR REPLACE FUNCTION CREAR_EXAM
  (
      ID_E    IN NUMBER
    , FECHA_E IN TIMESTAMP
    , INSTRUCCIONES_E IN VARCHAR2
    , PUBLICADO_E IN NUMBER
    , ID_SUBAREA_E IN NUMBER
    , TITULO_E IN VARCHAR2
  ) RETURN NUMBER --RETORNARA UN NUMERO
IS
  BEGIN

    INSERT INTO EXAM (ID,FECHA,INSTRUCCIONES,PUBLICADO,SUB_AREA_ID,TITULO)
    VALUES    (ID_E,FECHA_E,INSTRUCCIONES_E,PUBLICADO_E,ID_SUBAREA_E,TITULO_E);

    RETURN 0; -- 0 SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1; --SIGNIFICA ERROR

  END CREAR_EXAM;