create or replace FUNCTION CREAR_JOB_PRO_LANG
  (
      ID_LENGUAJE       IN LANGUAGES.LANGUAGE_ID%TYPE
    , ID_NIVEL          IN LANGUAGE_LEVEL.LANGUAGE_LEVEL_ID%TYPE
    , ID_PERFIL         IN JOB_PROFILES.ID%TYPE
  ) RETURN NUMBER
IS

  V_BOOL NUMBER;
  BEGIN


    INSERT  INTO JOB_PROFILES_LANGUAGES(ID,LANGUAGE_LEVEL_ID,LANGUAJE_ID)
    VALUES(ID_PERFIL,ID_NIVEL,ID_LENGUAJE);

    V_BOOL := 0;
    RETURN V_BOOL; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN -3; -- ya existe el registro para este perfil


  END CREAR_JOB_PRO_LANG;