create or replace FUNCTION CREAR_INSTITUCION
  (
      ID_I    IN NUMBER
    , NOMBRE  IN VARCHAR2
    , CODIGO  IN VARCHAR2
    , TIPO    IN VARCHAR2
  ) RETURN NUMBER
IS
  V_BOOL NUMBER;
  BEGIN

    INSERT INTO INSTITUTION (ID,INSTITUTION_CODE,INSTITUTION_NAME,INSTITUTION_TYPE)
    VALUES    (ID_I,CODIGO,NOMBRE,TIPO);

    V_BOOL := 0;
    RETURN V_BOOL; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1; --SIGNIFICA ERROR

  END CREAR_INSTITUCION;