CREATE OR REPLACE FUNCTION CREAR_AREA
  (
      ID_A    IN NUMBER --PARAMETRO DE LA FUNCION
    , NOMBRE  IN VARCHAR2 --PARAMETRO DE LA FUNCION
  ) RETURN NUMBER --RETORNARA UN NUMERO
IS
  BEGIN
    ---INGRESA EL REGISTRO A LA TABLA--
    INSERT INTO AREA (ID,NOMBRE)
    VALUES    (ID_A,NOMBRE);

    --SI SE INGRESA ENTONCES SE RETORNA 0--
    RETURN 0; -- 0 SIGNIFICA CORRECTO

    --SI HUBO ALGUN PROBLEMA SE ACTIVA LA EXCEPCION Y SE RETORNA 1--
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1; --SIGNIFICA ERROR

  END CREAR_AREA;