CREATE OR REPLACE FUNCTION CREAR_PREGUNTA
  (
      ID_Q IN NUMBER
    , D1_Q IN VARCHAR2
    , D2_Q IN VARCHAR2
    , D3_Q IN VARCHAR2
    , D4_Q IN VARCHAR2
    , ENUNCIADO_Q IN VARCHAR2
    , PESO_Q IN NUMBER
    , RESPUESTA_Q IN VARCHAR2
    , SUBAREA_ID_Q IN NUMBER
  ) RETURN NUMBER
IS
  ---DECLARACION DE VARIABLES--
  BEGIN

    INSERT INTO QUESTION(ID,D1,D2,D3,D4,ENUNCIADO,PESO,RESPUESTA,SUB_AREA_ID)
    VALUES      (ID_Q,D1_Q,D2_Q,D3_Q,D4_Q,ENUNCIADO_Q,PESO_Q,RESPUESTA_Q,SUBAREA_ID_Q);

    RETURN 0; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1;  --SIGNIFICA ERROR

  END CREAR_PREGUNTA;