create or replace FUNCTION CREAR_JOB_PRO_SKILL
  (
      ID_HABILIDAD      IN SKILL.SKILL_ID%TYPE
    , NOMBRE_HABILIDAD  IN SKILL.TITULO%TYPE
    , ID_PERFIL         IN JOB_PROFILES.ID%TYPE
    , ID_CATEGORIA      IN SKILL_CATEGORY.SKILL_CATEGORY_ID%TYPE
  ) RETURN NUMBER
IS
  V_HAB_ID SKILL.SKILL_ID%TYPE := -100;
  V_JPRO_ID JOB_PROFILES.ID%TYPE := -100;
  V_BOOL NUMBER;
  BEGIN


    select 1 into V_JPRO_ID FROM JOB_PROFILES WHERE ID = ID_PERFIL;

    select 1 into V_HAB_ID FROM SKILL WHERE SKILL_ID = ID_HABILIDAD;

    INSERT  INTO JOB_PROFILES_SKILLS(JOB_PROFILE_ID,SKILL_SKILL_ID)
    VALUES(ID_PERFIL,ID_HABILIDAD);

    V_BOOL := 0;
    RETURN V_BOOL; --SIGNIFICA CORRECTO

    EXCEPTION
    WHEN NO_DATA_FOUND THEN

    if V_HAB_ID = -100 then
      V_BOOL := -1; -- NO ESTA LA HABILIDAD
    end if;

    if V_JPRO_ID = -100 then
      V_BOOL := -2; -- NO ESTA EL PERFIL
    end if;

    RETURN V_BOOL;

    WHEN DUP_VAL_ON_INDEX THEN
    RETURN -3; -- ya existe el registro para este perfil


  END CREAR_JOB_PRO_SKILL;