create or replace FUNCTION CREAR_PERFIL_TRABAJO
  (
    NOMBRE      IN JOB_PROFILES.NAME%TYPE,
    DESCRIPCION IN JOB_PROFILES.DESCRIPTION%TYPE,
    EDAD_MAX    IN JOB_PROFILES.MAX_AGE%TYPE,
    EDAD_MIN    IN JOB_PROFILES.MIN_AGE%TYPE,
    EDUC_MIN    IN JOB_PROFILES.STATE_OF_EDUCATION%TYPE,
    COMPAÑIA_ID IN JOB_PROFILES.COMPANY_ID%TYPE
  ) RETURN NUMBER
IS
  V_BOOL NUMBER;
  V_ERROR_COMP NUMBER;
  V_JP_ID JOB_PROFILES.ID%TYPE;
  V_JP_CODIGO JOB_PROFILES.CODE%TYPE;

    E_DES_MUY_LARGA EXCEPTION;
    E_DE_EDAD       EXCEPTION;
    E_MAX_MIN       EXCEPTION;
    E_DES_LARGA     EXCEPTION;
    E_EDUC_MIN      EXCEPTION;
  BEGIN

    SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_JP_ID FROM DUAL;

    IF EDAD_MAX < 18 OR EDAD_MAX >= 100 THEN
      RAISE E_DE_EDAD;
    END IF;
    IF EDAD_MIN < 18 OR EDAD_MIN >= 100 THEN
      RAISE E_DE_EDAD;
    END IF;

    IF EDAD_MAX < EDAD_MIN THEN
      RAISE E_MAX_MIN;
    END IF;

    SELECT 1 into V_ERROR_COMP FROM USERS WHERE ID = COMPAÑIA_ID;

    IF UPPER(EDUC_MIN) NOT IN ('BACHILLER','UNIVERSITARIO_1','UNIVERSITARIO_2',
                               'UNIVERSITARIO_3',
                               'UNIVERSITARIO_4',
                               'UNIVERSITARIO_5',
                               'EGRESADO','GRADUADO') THEN
      RAISE E_EDUC_MIN;
    END IF;


    V_JP_CODIGO := CREATE_SLUG(LOWER(NOMBRE) || ' ' || TO_CHAR(COMPAÑIA_ID));

    insert into JOB_PROFILES(ID,CODE,DESCRIPTION,MAX_AGE,MIN_AGE,NAME,COMPANY_ID,STATE_OF_EDUCATION)
    VALUES (V_JP_ID,V_JP_CODIGO,DESCRIPCION,EDAD_MAX,EDAD_MIN,LOWER(NOMBRE),COMPAÑIA_ID,EDUC_MIN);

    RETURN V_JP_ID; -- NO HAY PEDO

    EXCEPTION

    WHEN NO_DATA_FOUND THEN

    RETURN -4; --COMPAÑIA NO ENCONTRADA

    WHEN DUP_VAL_ON_INDEX THEN

    RETURN -1; --Valor duplicado

    WHEN E_DE_EDAD THEN

    RETURN -2; -- ERROR DE EDAD

    WHEN E_EDUC_MIN THEN

    RETURN -3; -- EDUC MIN NO VALIDO

    WHEN E_MAX_MIN THEN

    RETURN -5; -- La edad minima no puede superar la edad maxima

  END CREAR_PERFIL_TRABAJO;