create or replace FUNCTION CREAR_PERFIL_TRABAJO
  (
    NOMBRE      IN JOB_PROFILES.NAME%TYPE,
    DESCRIPCION IN JOB_PROFILES.DESCRIPTION%TYPE,
    EDAD_MAX    IN JOB_PROFILES.MAX_AGE%TYPE,
    EDAD_MIN    IN JOB_PROFILES.MIN_AGE%TYPE,
    COMPAÑIA_ID IN JOB_PROFILES.COMPANY_ID%TYPE
  ) RETURN NUMBER
IS
  V_BOOL NUMBER;
  V_JP_ID JOB_PROFILES.ID%TYPE;
  V_JP_CODIGO JOB_PROFILES.CODE%TYPE;
    E_DES_MUY_LARGA EXCEPTION;
    E_DE_EDAD EXCEPTION;
    E_DES_LARGA EXCEPTION;
  BEGIN

    SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_JP_ID FROM DUAL;

    IF EDAD_MAX < 18 OR EDAD_MAX >= 100 THEN
      RAISE E_DE_EDAD;
    END IF;
    IF EDAD_MIN < 18 THEN
      RAISE E_DE_EDAD;
    END IF;


    V_JP_CODIGO := CREATE_SLUG(LOWER(NOMBRE) || ' ' || TO_CHAR(COMPAÑIA_ID));

    insert into JOB_PROFILES(ID,CODE,DESCRIPTION,MAX_AGE,MIN_AGE,NAME,COMPANY_ID)
    VALUES (V_JP_ID,V_JP_CODIGO,DESCRIPCION,EDAD_MAX,EDAD_MIN,LOWER(NOMBRE),COMPAÑIA_ID);

    RETURN V_JP_ID; -- NO HAY PEDO

    EXCEPTION

    WHEN DUP_VAL_ON_INDEX THEN

    RETURN -1; --Valor duplicado

    WHEN E_DE_EDAD THEN

    RETURN -2; -- ERROR DE EDAD


  END CREAR_PERFIL_TRABAJO;