CREATE OR REPLACE FUNCTION CREAR_CUESTIONARIO
  (
      ID_C    IN NUMBER
    , EXAM_ID_C IN NUMBER
    , QUESTION_ID_C  IN NUMBER
  ) RETURN NUMBER --RETORNARA UN NUMERO
IS
  BEGIN

    INSERT INTO QUESTIONARY (ID,EXAM_ID,QUESTION_ID)
    VALUES    (ID_C,EXAM_ID_C,QUESTION_ID_C);

    RETURN 0; -- 0 SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1; --SIGNIFICA ERROR

  END CREAR_CUESTIONARIO;