CREATE OR REPLACE FUNCTION CREAR_SUBAREA
  (
      ID_SA    IN NUMBER
    , ID_AREA_SA IN NUMBER
    , NOMBRE  IN VARCHAR2
  ) RETURN NUMBER --RETORNARA UN NUMERO
IS
  BEGIN

    INSERT INTO SUB_AREA (ID,AREA_ID,NOMBRE)
    VALUES    (ID_SA,ID_AREA_SA,NOMBRE);

    RETURN 0; -- 0 SIGNIFICA CORRECTO

    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    RETURN 1; --SIGNIFICA ERROR

  END CREAR_SUBAREA;