create or replace FUNCTION CREAR_EXP_ACADEMICA_PERFIL
  (
      ID_PERFIL IN JOB_PROFILES.ID%TYPE
    , ID_TITULO  IN ACADEMIC_TITLES.TITLE_ID%TYPE
  ) RETURN NUMBER IS
  V_BOOL NUMBER;
  V_JPRO_ID    JOB_PROFILES.ID%TYPE            := -100;
  V_TITLE_ID  ACADEMIC_TITLES.TITLE_ID%TYPE   := -100;
  BEGIN

    select 1 into V_JPRO_ID FROM JOB_PROFILES WHERE ID = ID_PERFIL;

    select 1 into V_TITLE_ID FROM ACADEMIC_TITLES WHERE TITLE_ID = ID_TITULO;

    INSERT INTO ACADEMIC_EXPERIENCES_PROFILES(JOB_PROFILE_ID,TITLE_TITLE_ID)
    VALUES(ID_PERFIL,ID_TITULO);

    V_BOOL := 0;
    RETURN V_BOOL;

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    if V_TITLE_ID = -100 then
      V_BOOL := -1; -- NO ESTA EL TITULO
    end if;

    if V_JPRO_ID = -100 then
      V_BOOL := -2; -- NO ESTA EL PERFIL
    end if;

    RETURN V_BOOL;

    WHEN DUP_VAL_ON_INDEX THEN
    RETURN -3; -- ya existe el registro


  END CREAR_EXP_ACADEMICA_PERFIL;