create or replace FUNCTION ENCONTRAR_CARGO
  (
    ID_CARGO IN VARCHAR2
  ) RETURN JOB.JOB_ID%TYPE
IS
  V_CA_ID JOB.JOB_ID%TYPE;
  BEGIN

    SELECT JOB_ID INTO V_CA_ID FROM JOB WHERE JOB_ID = ID_CARGO;

    RETURN V_CA_ID;

    EXCEPTION

    WHEN no_data_found THEN

    RETURN 0;

  END ENCONTRAR_CARGO;